name: vnoaob
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - scipy
  - jupyter
  - ipython
  - plotly
  - xarray 
  - pandas
  - scikit-learn
  - minian
  - seaborn